/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>

public Plugin:myinfo = 
{
	name = "COD Perk Block",
	author = "d0naciak",
	description = "Plugin blocks getting perks on some classes.",
	version = "1.0",
	url = "none"
}

char g_blocksListClasses[][] = {
	"[P] Kapitan",
	"[P] Kapitan",
	"[P] Tajniak",
	"[P] Tajniak",
	"[P] Tajniak",
	"[P] Tajniak",
	"[P] Tajniak",
	"Komandos",
	"Rakietnik",
	"Elektryk",
	"Snajper",
	"Szpieg",
	"Lekki Snajper"
};

char g_blocksListPerks[][] = {
	"Wyposażenie Kapitana",
	"Kamuflaż stopniowany",
	"Nóż Komandosa",
	"Kret z niespodzianką",
	"Skrzydła Archanioła",
	"Tajemnica Elektryka",
	"Zestaw Rakietnika",
	"Kamuflaż stopniowany",
	"Zestaw Rakietnika",
	"Tajemnica Elektryka",
	"Kamuflaż stopniowany",
	"Prochy Al-Kaida",
	"Kamuflaż stopniowany"
};

int g_blocksList[128][2];

public void OnPluginStart() {
	CreateTimer(1.0, timer_ReadIndexes);
}

public Action timer_ReadIndexes(Handle timer) {
	for(int i = 0; i < sizeof g_blocksListClasses; i++) {
		g_blocksList[i][0] = CodD0_GetClassID(g_blocksListClasses[i]);
		g_blocksList[i][1] = CodD0_GetPerkID(g_blocksListPerks[i]);
	}
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	CreateTimer(1.0, timer_Check, client);
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	CreateTimer(1.0, timer_Check, client);
}

public Action timer_Check(Handle timer, any client) {
	if(!IsClientInGame(client)) {
		return Plugin_Continue;
	}
	
	for (int i = 0; i < sizeof g_blocksListClasses; i++) {
		if(CodD0_GetClientClass(client) == g_blocksList[i][0] && CodD0_GetClientPerk(client) == g_blocksList[i][1]) {
			CodD0_SetClientPerk(client);
			break;
		}
	}
	
	return Plugin_Continue;
}