/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>

public Plugin myinfo =  {
	name = "CodD0 Perk: Cheater's pack",
	author = "d0naciak",
	description = "Cheater's pack",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Zestaw Czitera", "Dostajesz 2 granaty taktyczne");
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	static bool hasPerk[MAXPLAYERS + 1];

	if (perkID == g_perkID) {
		if (!hasPerk[client]) {
			CodD0_GiveClientWeapon(client, CSWeapon_TAGGRENADE);
			CodD0_GiveClientWeapon(client, CSWeapon_TAGGRENADE);
			hasPerk[client] = true;
		}
	} else if (hasPerk[client]) {
		CodD0_TakeClientWeapon(client, CSWeapon_TAGGRENADE);
		CodD0_TakeClientWeapon(client, CSWeapon_TAGGRENADE);
		hasPerk[client] = false
	}
}