/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_damage>

public Plugin myinfo =  {
	name = "CodD0 Perk: Captain's notes",
	author = "d0naciak",
	description = "Captain's notes",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_hasPerk[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Notatki Kapitana", "Odbijasz pierwsze 2 pociski co runde. Perk bardzo rzadki do zdobycia", 0, 4);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public Action CodD0_PerkChanged(int client, int perkID, int perkValue) {
	if(g_perkID != perkID) {
		if(g_hasPerk[client]) {
			CodD0_SetClientBulletsToBounce(client, CodD0_SkillSlot_Perk, 0);
			g_hasPerk[client] = false;
		}
	} else {
		return Plugin_Handled;
	}
	
	return Plugin_Continue;
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	if (perkID == g_perkID) {
		CodD0_SetClientBulletsToBounce(client, CodD0_SkillSlot_Perk, 2);
		g_hasPerk[client] = true;
	}
}