/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_damage>

public Plugin myinfo =  {
	name = "CodD0 Perk: Al-Kaida's ashers",
	author = "d0naciak",
	description = "Al-Kaida's ashers",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_hasPerk[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Prochy Al-Kaida", "Twoje granaty wybuchowe zabijają natychmiastowo");
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public Action CodD0_PerkChanged(int client, int perkID, int perkValue) {
	if(g_perkID != perkID && g_hasPerk[client]) {
		CodD0_SetClientChanceToKill(client, CodD0_SkillSlot_Perk, CSWeapon_HEGRENADE, 0);
		CodD0_TakeClientWeapon(client, CSWeapon_HEGRENADE);
		g_hasPerk[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	if (perkID == g_perkID && !g_hasPerk[client]) {
		CodD0_SetClientChanceToKill(client, CodD0_SkillSlot_Perk, CSWeapon_HEGRENADE, 1);
		CodD0_GiveClientWeapon(client, CSWeapon_HEGRENADE);
		g_hasPerk[client] = true;
	}
}