/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_blindingWave>

public Plugin myinfo =  {
	name = "CodD0 Perk: Flash",
	author = "d0naciak",
	description = "Flash",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_hasPerk[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Rozbłysk", "Użyj, a wszyscy przeciwnicy w zasięgu ~8m zostaną oślepieni");
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public Action CodD0_PerkChanged(int client, int perkID, int perkValue) {
	if(g_perkID != perkID && g_hasPerk[client]) {
		CodD0_SetClientBlindingWaves(client, CodD0_SkillSlot_Perk, 0, 0.0);
		g_hasPerk[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	if (perkID == g_perkID && !g_hasPerk[client]) {
		CodD0_SetClientBlindingWaves(client, CodD0_SkillSlot_Perk, 99, 500.0);
		g_hasPerk[client] = true;
	}
}

public void CodD0_PerkUsed(int client, int perkID) {
	if (!g_hasPerk[client]) {
		return;
	}

	if (CodD0_UseBlindingWaves(client, CodD0_SkillSlot_Perk) == CodD0_SkillPrep_Available) {
		CodD0_ClientPerkGotReady(client, 30.0);
	}
}