/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_bonusesForFrags>

public Plugin myinfo =  {
	name = "CodD0 Perk: Rich",
	author = "d0naciak",
	description =  "Rich",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Bogacz", "Dostajesz bonusowe +LW monet za fraga", 2, 4);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	static int perkLastValue[MAXPLAYERS + 1];

	if (g_perkID == perkID) {
		CodD0_SetClientCoinsForFrag(client, CodD0_GetClientCoinsForFrag(client) + perkValue - perkLastValue[client]);
		perkLastValue[client] = perkValue;
	} else if (perkLastValue[client]) {
		CodD0_SetClientCoinsForFrag(client, CodD0_GetClientCoinsForFrag(client) - perkLastValue[client]);
		perkLastValue[client] = 0;
	}
}