/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdkhooks>
#include <CodD0_engine>

public Plugin myinfo =  {
	name = "CodD0 Perk: Nanosuit",
	author = "d0naciak",
	description = "Nanosuit",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_hasPerk[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Nanokamizelka", "Jesteś odporny na wszystkie umiejętności klas/perków, czyli pioruny, rakiety, itd. Perk bardzo rzadki do zdobycia", 0, 2);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public Action CodD0_PerkChanged(int client, int perkID, int perkValue) {
	if (perkID == g_perkID) {
		if (perkValue) {
			return Plugin_Handled;
		}

		if (!g_hasPerk[client]) {
			SDKHook(client, SDKHook_OnTakeDamage, ev_OnTakeDamage);
		}

		g_hasPerk[client] = true;
	} else if (g_hasPerk[client]) {
		SDKUnhook(client, SDKHook_OnTakeDamage, ev_OnTakeDamage);
		g_hasPerk[client] = false;
	}
	
	return Plugin_Continue;
}

public Action ev_OnTakeDamage(int victim, int &attacker, int &ent, float &damage, int &damageType, int &weapon, float damageForce[3], float damagePos[3], int damageCustom) {
	if (attacker <= 0 || attacker > MAXPLAYERS || !IsClientInGame(attacker) || GetClientTeam(attacker) == GetClientTeam(victim)) {
		return Plugin_Continue;
	}

	if(damageType & (1<<31)) {
		attacker = 0;
		damageType = 0;
		damage = 0.0;
		return Plugin_Changed;
	}

	return Plugin_Continue;
}