/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdkhooks>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_bonusesForFrags>

public Plugin myinfo =  {
	name = "CodD0 Perk: Lieutenant Skill",
	author = "d0naciak",
	description = "Lieutenant Skill",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
int g_perkValue[MAXPLAYERS + 1], g_perkLastBonus[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Skill Porucznika", "Za każdego fraga zgarniasz LW (+int) ammo", 4, 16);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	if(perkID == g_perkID) {
		if (!g_perkLastBonus[client]) {
			SDKHook(client, SDKHook_SpawnPost, ev_Spawn_Post);
		}

		int bonus = perkValue + RoundFloat(float(CodD0_GetClientBonusStatsPoints(client, INT_PTS)) * 0.05);

		CodD0_SetClientAmmoForFrag(client, CodD0_GetClientAmmoForFrag(client) + bonus - g_perkLastBonus[client]);
		g_perkLastBonus[client] = bonus;
		g_perkValue[client] = perkValue;
	} else if(g_perkLastBonus[client]) {
		SDKUnhook(client, SDKHook_SpawnPost, ev_Spawn_Post);
		CodD0_SetClientAmmoForFrag(client, CodD0_GetClientAmmoForFrag(client) - g_perkLastBonus[client]);
		g_perkLastBonus[client] = 0;
	}
}

public void ev_Spawn_Post(int client) {
	int bonus = g_perkValue[client] + RoundFloat(float(CodD0_GetClientBonusStatsPoints(client, INT_PTS)) * 0.05);
	CodD0_SetClientAmmoForFrag(client, CodD0_GetClientAmmoForFrag(client) + bonus - g_perkLastBonus[client]);
	g_perkLastBonus[client] = bonus;
}