/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_poisoning>

public Plugin myinfo =  {
	name = "CodD0 Perk: Poisoned smokes",
	author = "d0naciak",
	description =  "Poisoned smokes",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_hasPerk[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Trujące smoki", "Twoje smoke'i otruwają przeciwników (standardowo dostajesz 2 smoke)");
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public Action CodD0_PerkChanged(int client, int perkID, int perkValue) {
	if(g_perkID != perkID && g_hasPerk[client]) {
		CodD0_SetClientPoisoningSmokes(client, CodD0_SkillSlot_Perk, false);
		CodD0_TakeClientWeapon(client, CSWeapon_SMOKEGRENADE);
		CodD0_TakeClientWeapon(client, CSWeapon_SMOKEGRENADE);
		g_hasPerk[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	if(g_perkID == perkID && !g_hasPerk[client]) {
		CodD0_SetClientPoisoningSmokes(client, CodD0_SkillSlot_Perk, true);

		if(!g_hasPerk[client]) {
			CodD0_GiveClientWeapon(client, CSWeapon_SMOKEGRENADE);
			CodD0_GiveClientWeapon(client, CSWeapon_SMOKEGRENADE);
		}

		g_hasPerk[client] = true;
	}
}