/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>

public Plugin myinfo =  {
	name = "CodD0 Perk: Commando shoes",
	author = "d0naciak",
	description =  "Commando shoes",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Buty Komandosa", "+LW do statystyki szybkości", 15, 45);
}

public OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	static int perkLastValue[MAXPLAYERS + 1];

	if(perkID == g_perkID) {
		CodD0_SetClientBonusStatsPoints(client, SPEED_PTS, CodD0_GetClientBonusStatsPoints(client, SPEED_PTS) + perkValue - perkLastValue[client]);
		perkLastValue[client] = perkValue;
	} else if(perkLastValue[client]) {
		CodD0_SetClientBonusStatsPoints(client, SPEED_PTS, CodD0_GetClientBonusStatsPoints(client, SPEED_PTS) - perkLastValue[client]);
		perkLastValue[client] = 0;
	}
}