/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>

public Plugin myinfo =  {
	name = "CodD0 Perk: Experience package",
	author = "d0naciak",
	description =  "Experience package",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_hasPerk[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Pakiet doświadczenia", "Co runde dostajesz ~1-250 doświadczenia");

	HookEvent("round_start", ev_RoundStart_Post);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	if (perkID == g_perkID) {
		g_hasPerk[client] = true;
	} else {
		g_hasPerk[client] = false;
	}
}

public void ev_RoundStart_Post(Handle event, const char[] eventName, bool dontBroadcast) {
	int expBonus;
	for (int i = 1; i <= MaxClients; i++) {
		if(!IsClientInGame(i) || !IsPlayerAlive(i) || !g_hasPerk[i]) {
			continue;
		}

		expBonus = GetRandomInt(1, 250);

		CodD0_SetClientExp(i, CodD0_GetClientExp(i) + expBonus);
		PrintToChat(i, " \x06\x05+%dXP\x01 za\x06 perka", expBonus);
	}
}