/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_bonusesForFrags>

public Plugin myinfo =  {
	name = "CodD0 Perk: Rare experience ring",
	author = "d0naciak",
	description = "Rare experience ring",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Rzadki pierścień doświadczenia", "Dostajesz +100 dośw. za zabójstwo", 0, 2);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public Action CodD0_PerkChanged(int client, int perkID, int perkValue) {
	if(g_perkID == perkID && !perkValue) {
		return Plugin_Handled;
	}
	
	return Plugin_Continue;
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	static bool hasPerk[MAXPLAYERS + 1];
	if (perkID == g_perkID) {
		if (!hasPerk[client]) {
			CodD0_SetClientExpForFrag(client, CodD0_GetClientExpForFrag(client) + 100);
			hasPerk[client] = true;
		}
	} else if (hasPerk[client]) {
		CodD0_SetClientExpForFrag(client, CodD0_GetClientExpForFrag(client) - 100);
		hasPerk[client] = false;
	}
}