/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_noClip>

public Plugin myinfo =  {
	name = "CodD0 Perk: Death Corporal Ghost",
	author = "d0naciak",
	description =  "Death Corporal Ghost",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_hasPerk[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Duch martwego Kaprala", "Użyj, a będziesz mógł przenikać przez ściany przez LW sec", 5, 10);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public Action CodD0_PerkChanged(int client, int perkID, int perkValue) {
	if(g_perkID != perkID && g_hasPerk[client]) {
		CodD0_SetClientNoClips(client, CodD0_SkillSlot_Perk, 0, 0.0);
		g_hasPerk[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	if(g_perkID == perkID) {
		CodD0_SetClientNoClips(client, CodD0_SkillSlot_Perk, 99, float(perkValue));
		g_hasPerk[client] = true;
	}
}

public void CodD0_PerkUsed(int client, int perkID) {
	if(!g_hasPerk[client]) {
		return;
	}

	CodD0_UseNoClip(client, CodD0_SkillSlot_Perk);
}

public void CodD0_EndOfNoClip(int client, int CodD0_SkillSlot, int CodD0_SkillPrep) {
	if(!g_hasPerk[client] || CodD0_SkillSlot != CodD0_SkillSlot_Perk) {
		return;
	}

	if(CodD0_SkillPrep == CodD0_SkillPrep_Available) {
		CodD0_ClientPerkGotReady(client, 16.0);
	}
}