/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>

public Plugin myinfo =  {
	name = "CodD0 Perk: Medkit",
	author = "d0naciak",
	description =  "Medkit",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_used[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Apteczka", "Użyj, aby uleczyć się w 100%. Dostępne raz na runde");

	HookEvent("round_start", ev_RoundStart_Post);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public void ev_RoundStart_Post(Handle event, const char[] name, bool dontBroadcast) {
	for(int i = 1; i <= MaxClients; i++) {
		g_used[i] = false;
	}
}

public void CodD0_PerkUsed(int client, int perkID) {
	if (g_perkID != perkID) {
		return;
	}
	
	if (g_used[client]) {
		PrintCenterText(client, "Perk jest dostępny tylko raz na rundę!");
		return;
	}

	SetEntityHealth(client, 100 + CodD0_GetAllClientStatsPoints(client, HEALTH_PTS));
	g_used[client] = true;
}