/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_exploding>

public Plugin myinfo =  {
	name = "CodD0 Perk: Ticking bomb",
	author = "d0naciak",
	description = "Ticking bomb",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_perkID;
bool g_hasPerk[MAXPLAYERS + 1];
public void OnPluginStart() {
	g_perkID = CodD0_RegisterPerk("Tykająca bomba", "Wybuchasz po śmierci zadając LW dmg", 80, 160);
	HookEvent("player_death", ev_PlayerDeath_Post);
}

public void OnPluginEnd() {
	CodD0_UnregisterPerk(g_perkID);
}

public Action CodD0_PerkChanged(int client, int perkID, int perkValue) {
	if(g_perkID != perkID && g_hasPerk[client]) {
		CodD0_SetClientExplodes(client, CodD0_SkillSlot_Perk, 0, 0.0, 0.0, 0);
		g_hasPerk[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_PerkChanged_Post(int client, int perkID, int perkValue) {
	if (perkID == g_perkID) {
		CodD0_SetClientExplodes(client, CodD0_SkillSlot_Perk, 1, float(perkValue), 0.5, EXPLO_PLAYER);
		g_hasPerk[client] = true;
	}
}

public void ev_PlayerDeath_Post(Handle event, const char[] name, bool dontBroadcast) {
	int client = GetClientOfUserId(GetEventInt(event, "userid"));

	if(client && g_hasPerk[client]) {
		CodD0_UseExplode(client, CodD0_SkillSlot_Perk);
	}
}