/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_burning>
#include <CodD0/skills/CodD0_skill_blinding>

public Plugin myinfo =  {
	name = "CodD0 Class: Taleb",
	author = "d0naciak",
	description =  "Taleb",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Talib", "1/8 szans na podpalenie przeciwnika, odporny na oślepienia", {5, 15, 0, 10}, { CSWeapon_AK47, CSWeapon_FIVESEVEN, CSWeapon_MOLOTOV, CSWeapon_MOLOTOV }, 4);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientChanceToBurn(client, CodD0_SkillSlot_Class, 0);
		CodD0_SetClientNoFlash(client, CodD0_SkillSlot_Class, false);
		g_hasClass[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientChanceToBurn(client, CodD0_SkillSlot_Class, 8);
		CodD0_SetClientNoFlash(client, CodD0_SkillSlot_Class, true);
		g_hasClass[client] = true;
	}
}