/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_freezing>
#include <CodD0/skills/CodD0_skill_damage>

public Plugin myinfo =  {
	name = "CodD0 Class: Guerilla",
	author = "d0naciak",
	description =  "Guerilla",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Partyzant", "1/11 szans na zamrożenie przeciwnika, 1/7 szansy na uniknięcie pocisku", {10, 15, 35, 20}, { CSWeapon_GALILAR, CSWeapon_REVOLVER, CSWeapon_SMOKEGRENADE, CSWeapon_INCGRENADE }, 4);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientChanceToDodgeBullet(client, CodD0_SkillSlot_Class, 0);
		CodD0_SetClientChanceToFreeze(client, CodD0_SkillSlot_Class, 0);
		g_hasClass[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientChanceToDodgeBullet(client, CodD0_SkillSlot_Class, 7);
		CodD0_SetClientChanceToFreeze(client, CodD0_SkillSlot_Class, 11);
		g_hasClass[client] = true;
	}
}