/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_chanceToKillOppnntWithKnife>
#include <CodD0/skills/CodD0_skill_damage>
#include <CodD0/skills/CodD0_skill_visibility>

public Plugin myinfo =  {
	name = "CodD0 Class: Sniper",
	author = "d0naciak",
	description =  "Sniper",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];
public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Snajper", "Zmniejszona widoczność, AWP obr. +int, zabija z AWP jeżeli przeciwnik trzyma nóż", {10, 25, 5, 10}, { CSWeapon_AWP, CSWeapon_P250, CSWeapon_FLASHBANG }, 3);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientVisibility(client, CodD0_SkillSlot_Class, 255);
		CodD0_SetClientIntDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_AWP, 0.0);
		CodD0_SetClientChanceToKillOppnntWithKnife(client, CodD0_SkillSlot_Class, CSWeapon_AWP, 0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientVisibility(client, CodD0_SkillSlot_Class, 125);
		CodD0_SetClientIntDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_AWP, 0.45);
		CodD0_SetClientChanceToKillOppnntWithKnife(client, CodD0_SkillSlot_Class, CSWeapon_AWP, 1);
		g_hasClass[client] = true;
	}
}