/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_replicas>

public Plugin myinfo =  {
	name = "CodD0 Class: Replicant",
	author = "d0naciak",
	description =  "Replicant",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];
public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Replikant", "Może postawić 4 kukły, które odbijają obrażenia. Można je zniszczyć nożem", {0, 0, 25, 25}, { CSWeapon_AUG, CSWeapon_FIVESEVEN, CSWeapon_FLASHBANG }, 3);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientReplicas(client, CodD0_SkillSlot_Class, 0, 0.0, 0.0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientReplicas(client, CodD0_SkillSlot_Class, 4, 16.0, 0.16);
		g_hasClass[client] = true;
	}
}

public void CodD0_ClassSkillUsed(int client, int classID) {
	if(!g_hasClass[client]) {
		return;
	}

	if(CodD0_PlaceReplica(client, CodD0_SkillSlot_Class) == CodD0_SkillPrep_Available) {
		CodD0_ClientClassSkillGotReady(client, 6.0);
	}
}