/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_mine>

public Plugin myinfo =  {
	name = "CodD0 Class: Sapper",
	author = "d0naciak",
	description =  "Sapper",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];
public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Saper", "Posiada 5 min (120 obr. +int)", {10, 10, 5, 10}, { CSWeapon_M4A1, CSWeapon_P250 }, 2);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientMines(client, CodD0_SkillSlot_Class, 0, 0.0, 0.0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientMines(client, CodD0_SkillSlot_Class, 5, 120.0, 0.5);
		g_hasClass[client] = true;
	}
}

public void CodD0_ClassSkillUsed(int client, int classID) {
	if(!g_hasClass[client]) {
		return;
	}

	CodD0_PlantMine(client, CodD0_SkillSlot_Class);
}