/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_damage>
#include <CodD0/skills/CodD0_skill_chanceToScreenShake>
#include <CodD0/skills/CodD0_skill_noFallDamage>

public Plugin myinfo =  {
	name = "CodD0 Class: Heavy Soldier",
	author = "d0naciak",
	description =  "Heavy Soldier",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Ciężki Żołnierz", "Odporny na upadki oraz strzały w nogi, 1/14 na wstrząs ekranu przeciwnika", {0, 30, 30, 0}, { CSWeapon_NEGEV, CSWeapon_CZ75A, CSWeapon_HEGRENADE, CSWeapon_HEGRENADE, CSWeapon_MOLOTOV }, 5);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientNoFallDamage(client, CodD0_SkillSlot_Class, false);
		CodD0_SetClientHitBoxRedDmgMultiplier(client, CodD0_SkillSlot_Class, HIT_LEFTLEG, 1.0); 
		CodD0_SetClientHitBoxRedDmgMultiplier(client, CodD0_SkillSlot_Class, HIT_RIGHTLEG, 1.0);
		CodD0_SetClientChanceToScreenShake(client, CodD0_SkillSlot_Class, 0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientNoFallDamage(client, CodD0_SkillSlot_Class, true);
		CodD0_SetClientHitBoxRedDmgMultiplier(client, CodD0_SkillSlot_Class, HIT_LEFTLEG, 0.0); 
		CodD0_SetClientHitBoxRedDmgMultiplier(client, CodD0_SkillSlot_Class, HIT_RIGHTLEG, 0.0);
		CodD0_SetClientChanceToScreenShake(client, CodD0_SkillSlot_Class, 14);
		g_hasClass[client] = true;
	}
}