/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_damage>
#include <CodD0/skills/CodD0_skill_unlimitedAmmo>

public Plugin myinfo =  {
	name = "CodD0 Class: Rusher",
	author = "d0naciak",
	description =  "Rusher",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];
public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Rusher", "Bezlik ammo w XM1014, obrażenia z XM1014 +int", {15, 20, 15, 30}, { CSWeapon_XM1014, CSWeapon_TEC9, CSWeapon_DECOY }, 3);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientUnlimitedAmmo(client, CodD0_SkillSlot_Class, false);
		CodD0_SetClientIntDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_XM1014, 0.0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientUnlimitedAmmo(client, CodD0_SkillSlot_Class, true);
		CodD0_SetClientIntDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_XM1014, 0.075);
		g_hasClass[client] = true;
	}
}