/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_unlimitedAmmo>
#include <CodD0/skills/CodD0_skill_multiJump>
#include <CodD0/skills/CodD0_skill_damage>

public Plugin myinfo =  {
	name = "CodD0 Class: [P] Indestructible",
	author = "d0naciak",
	description =  "[P] Indestructible",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("[P] Niezniszczalny", "Nieskończona amunicja, podwójny skok, +5 obr. z M4", {0, 30, 30, 80}, { CSWeapon_M4A1_SILENCER, CSWeapon_HKP2000, CSWeapon_FLASHBANG }, 3);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID == classID) {
		if(!CheckCommandAccess(client, "sm_klasa_niezniszczalny", ADMFLAG_CUSTOM3)) {
			PrintToChat(client, " \x06\x04[COD:MW]\x01 Aby skorzystać z tej klasy, użyj komendy \x05!sklepsms");
			return Plugin_Handled;
		}
	} else if (g_hasClass[client]) {
		CodD0_SetClientDmgBonus(client, CodD0_SkillSlot_Class, CSWeapon_M4A1_SILENCER, 0);
		CodD0_SetClientMultiJumps(client, CodD0_SkillSlot_Class, 0);
		CodD0_SetClientUnlimitedAmmo(client, CodD0_SkillSlot_Class, false);
		g_hasClass[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientDmgBonus(client, CodD0_SkillSlot_Class, CSWeapon_M4A1_SILENCER, 5);
		CodD0_SetClientMultiJumps(client, CodD0_SkillSlot_Class, 1);
		CodD0_SetClientUnlimitedAmmo(client, CodD0_SkillSlot_Class, true);
		g_hasClass[client] = true;
	}
}