/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_bonusesForFrags>
#include <CodD0/skills/CodD0_skill_bonusesForDamage>
#include <CodD0/skills/CodD0_skill_damage>
#include <CodD0/skills/CodD0_skill_silentFootsteps>

public Plugin myinfo =  {
	name = "CodD0 Class: [P] Vampire",
	author = "d0naciak",
	description =  "[P] Vampire",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("[P] Wampir", "Pełen magazynek za fraga, za HeadShota zgarnia +10 HP oraz +45 obrażeń. Ciche kroki", {0, 30, 50, 30}, { CSWeapon_P90, CSWeapon_ELITE, CSWeapon_FLASHBANG, CSWeapon_FLASHBANG, CSWeapon_FLASHBANG }, 5);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID == classID) {
		if(!CheckCommandAccess(client, "sm_klasa_wampir", ADMFLAG_CUSTOM4)) {
			PrintToChat(client, " \x06\x04[COD:MW]\x01 Aby skorzystać z tej klasy, użyj komendy \x05!sklepsms");
			return Plugin_Handled;
		}
	} else if (g_hasClass[client]) {
		CodD0_SetClientSilentFootsteps(client, CodD0_SkillSlot_Class, false);
		CodD0_SetClientHitBoxDmgBonus(client, CodD0_SkillSlot_Class, HIT_HEAD, 0);
		CodD0_SetClientHealthForHeadShot(client, CodD0_GetClientHealthForHeadShot(client) - 10);
		CodD0_SetClientAmmoForFrag(client, CodD0_GetClientAmmoForFrag(client) - 99);
		g_hasClass[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID && !g_hasClass[client]) {
		CodD0_SetClientSilentFootsteps(client, CodD0_SkillSlot_Class, true);
		CodD0_SetClientHitBoxDmgBonus(client, CodD0_SkillSlot_Class, HIT_HEAD, 45);
		CodD0_SetClientHealthForHeadShot(client, CodD0_GetClientHealthForHeadShot(client) + 10);
		CodD0_SetClientAmmoForFrag(client, CodD0_GetClientAmmoForFrag(client) + 99);
		g_hasClass[client] = true;
	}
}