/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_healing>

public Plugin myinfo =  {
	name = "CodD0 Class: Medical",
	author = "d0naciak",
	description =  "Medical",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Medyk", "Podczas kucania w bezruchu bardzo szybko regeneruje zdrowie", {25, 80, 25, 0}, { CSWeapon_SG556, CSWeapon_P250, CSWeapon_DECOY, CSWeapon_SMOKEGRENADE }, 4);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientDuckHealing(client, CodD0_SkillSlot_Class, 0, 0.0, 0.0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientDuckHealing(client, CodD0_SkillSlot_Class, 4, 0.028, 0.5);
		g_hasClass[client] = true;
	}
}