/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_visibility>

public Plugin myinfo =  {
	name = "CodD0 Class: [P] Sleuth",
	author = "d0naciak",
	description =  "[P] Sleuth",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("[P] Tajniak", "Całkowicie niewidzialny na nożu, średnio widoczny z bronią", {0, 50, 50, 50}, { CSWeapon_NEGEV, CSWeapon_DEAGLE, CSWeapon_FLASHBANG, CSWeapon_FLASHBANG }, 4);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID == classID) {
		if(!CheckCommandAccess(client, "sm_klasa_tajniak", ADMFLAG_CUSTOM2)) {
			PrintToChat(client, " \x06\x04[COD:MW]\x01 Aby skorzystać z tej klasy, użyj komendy \x05!sklepsms");
			return Plugin_Handled;
		}
	} else if (g_hasClass[client]) {
		CodD0_SetClientVisibility(client, CodD0_SkillSlot_Class, 255);
		CodD0_SetClientVisibilityOnKnife(client, CodD0_SkillSlot_Class, 255);
		g_hasClass[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientVisibility(client, CodD0_SkillSlot_Class, 120);
		CodD0_SetClientVisibilityOnKnife(client, CodD0_SkillSlot_Class, 5);
		g_hasClass[client] = true;
	}
}