/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_damage>
#include <CodD0/skills/CodD0_skill_multiWeapons>

public Plugin myinfo =  {
	name = "CodD0 Class: [P] Captain",
	author = "d0naciak",
	description =  "[P] Captain",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("[P] Kapitan", "Użyj, aby zmienić broń na AWP/M4A4. Obrazenia z M4 +int, 3x większe z AWP", {10, 25, 10, 25}, { CSWeapon_M4A1, CSWeapon_AWP, CSWeapon_USP_SILENCER, CSWeapon_FLASHBANG }, 4);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {

	if (g_classID == classID) {
		if (!CheckCommandAccess(client, "sm_klasa_kapitan", ADMFLAG_CUSTOM5)) {
			PrintToChat(client, " \x06\x04[COD:MW]\x01 Aby skorzystać z tej klasy, użyj komendy \x05!sklepsms");
			return Plugin_Handled;
		}
	} else if (g_hasClass[client]) {
		CodD0_SetClientMultiWeapon(client, CS_SLOT_PRIMARY, 0, CSWeapon_NONE);
		CodD0_SetClientMultiWeapon(client, CS_SLOT_PRIMARY, 1, CSWeapon_NONE);
		CodD0_SetClientIntDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_M4A1, 0.0);
		CodD0_SetClientDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_AWP, 1.0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if (g_classID == classID) {
		CodD0_SetClientMultiWeapon(client, CS_SLOT_PRIMARY, 0, CSWeapon_M4A1);
		CodD0_SetClientMultiWeapon(client, CS_SLOT_PRIMARY, 1, CSWeapon_AWP);
		CodD0_SetClientIntDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_M4A1, 0.065);
		CodD0_SetClientDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_AWP, 3.0);
		g_hasClass[client] = true;
	}
}

public void CodD0_ClassSkillUsed(int client, int classID) {
	if(g_classID != classID) {
		return;
	}

	CodD0_ChangeClientWeapon(client, CS_SLOT_PRIMARY);
}