/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_silentFootsteps>
#include <CodD0/skills/CodD0_skill_damage>

public Plugin myinfo =  {
	name = "CodD0 Class: Spy",
	author = "d0naciak",
	description =  "Spy",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Szpieg", "Ciche kroki, granat obr. +int", {5, 10, 20, 15}, { CSWeapon_M4A1, CSWeapon_P250, CSWeapon_HEGRENADE, CSWeapon_HEGRENADE, CSWeapon_HEGRENADE }, 5);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientIntDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_HEGRENADE, 0.0);
		CodD0_SetClientSilentFootsteps(client, CodD0_SkillSlot_Class, false);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientIntDmgMultiplier(client, CodD0_SkillSlot_Class, CSWeapon_HEGRENADE, 0.2);
		CodD0_SetClientSilentFootsteps(client, CodD0_SkillSlot_Class, true);
		g_hasClass[client] = true;
	}
}