/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_damage>
#include <CodD0/skills/CodD0_skill_poisoning>

public Plugin myinfo =  {
	name = "CodD0 Class: [P] Posioner",
	author = "d0naciak",
	description =  "[P] Posioner",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("[P] Truciciel", "1/6 na otrucie, 1/2 na zabicie z Headshota", {30, 20, 30, 30}, { CSWeapon_AK47, CSWeapon_DEAGLE, CSWeapon_HEGRENADE, CSWeapon_MOLOTOV }, 4);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID == classID) {
		if(!CheckCommandAccess(client, "sm_klasa_truciciel", ADMFLAG_CUSTOM6)) {
			PrintToChat(client, " \x06\x04[COD:MW]\x01 Aby skorzystać z tej klasy, użyj komendy \x05!sklepsms");
			return Plugin_Handled;
		}
	} else if (g_hasClass[client]) {
		CodD0_SetClientChanceToPoison(client, CodD0_SkillSlot_Class, 0);
		CodD0_SetClientChanceToKillByHS(client, CodD0_SkillSlot_Class, CSWeapon_NONE, 0);
		g_hasClass[client] = false;
	}
	
	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientChanceToPoison(client, CodD0_SkillSlot_Class, 6);
		CodD0_SetClientChanceToKillByHS(client, CodD0_SkillSlot_Class, CSWeapon_NONE, 2);
		g_hasClass[client] = true;
	}
}