/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdkhooks>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_bonusesForFrags>

public Plugin myinfo =  {
	name = "CodD0 Class: Lieutenant",
	author = "d0naciak",
	description =  "Lieutenant",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];
int g_ammoBonus[MAXPLAYERS+1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Porucznik", "+8 (+int) ammo za fraga", {0, 15, 10, 20}, { CSWeapon_M4A1_SILENCER, CSWeapon_ELITE, CSWeapon_HEGRENADE, CSWeapon_FLASHBANG, CSWeapon_FLASHBANG }, 5);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientAmmoForFrag(client, CodD0_GetClientAmmoForFrag(client) - g_ammoBonus[client]);
		g_ammoBonus[client] = 0;
		SDKUnhook(client, SDKHook_SpawnPost, ev_Spawn_Post);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		int bonus = g_ammoBonus[client] = 8 + RoundFloat(float(CodD0_GetClientUsableIntelligence(client)) * 0.04);
		CodD0_SetClientAmmoForFrag(client, CodD0_GetClientAmmoForFrag(client) + bonus);
		SDKHook(client, SDKHook_SpawnPost, ev_Spawn_Post);
		g_hasClass[client] = true;
	}
}

public void ev_Spawn_Post(int client) {
	int bonus = 8 + RoundFloat(float(CodD0_GetClientUsableIntelligence(client)) * 0.04);
	CodD0_SetClientAmmoForFrag(client, CodD0_GetClientAmmoForFrag(client) - g_ammoBonus[client] + bonus);
	g_ammoBonus[client] = bonus;
}