/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_damage>
#include <CodD0/skills/CodD0_skill_gravity>
#include <CodD0/skills/CodD0_skill_ammoDestroying>

public Plugin myinfo =  {
	name = "CodD0 Class: Light Soldier",
	author = "d0naciak",
	description =  "Light Soldier",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Lekki Snajper", "Natychmiastowe zabicie z SSG08 po trafieniu HS, zmniejszona grawitacja, użyj umiejętności na przeciwniku, a jego ammo zniknie (dostępne co 10 sec.)", {0, 15, 15, 40}, { CSWeapon_SSG08, CSWeapon_USP_SILENCER, CSWeapon_FLASHBANG, CSWeapon_FLASHBANG }, 4);

}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientChanceToKillByHS(client, CodD0_SkillSlot_Class, CSWeapon_SSG08, 0);
		CodD0_SetClientGravity(client, CodD0_SkillSlot_Class, 1.0);
		CodD0_SetClientClipDestroyers(client, CodD0_SkillSlot_Class, 0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientChanceToKillByHS(client, CodD0_SkillSlot_Class, CSWeapon_SSG08, 1);
		CodD0_SetClientGravity(client, CodD0_SkillSlot_Class, 0.6);
		CodD0_SetClientClipDestroyers(client, CodD0_SkillSlot_Class, 99);
		g_hasClass[client] = true;
	}
}

public void CodD0_ClassSkillUsed(int client, int classID) {
	if(!g_hasClass[client]) {
		return;
	}

	if(CodD0_UseClipDestroyer(client, CodD0_SkillSlot_Class) == CodD0_SkillPrep_Available) {
		CodD0_ClientClassSkillGotReady(client, 10.0);
	}
}