/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <CodD0_engine>
#include <CodD0/skills/CodD0_skill_chanceToThrowUp>
#include <CodD0/skills/CodD0_skill_chanceToEnemySkin>
#include <CodD0/skills/CodD0_skill_recoil>

public Plugin myinfo =  {
	name = "CodD0 Class: Kamikaze",
	author = "d0naciak",
	description =  "Kamikaze",
	version = "1.0",
	url = "d0naciak.pl"
}

int g_classID;
bool g_hasClass[MAXPLAYERS + 1];

public void OnPluginStart() {
	g_classID = CodD0_RegisterClass("Kamikadze", "Brak rozrzutu, 1/12 szansy na lekkie podrzucenie przeciwnika, ubranie wroga", {5, 20, 5, 80}, { CSWeapon_MP7, CSWeapon_ELITE }, 2);
}

public void OnPluginEnd() {
	CodD0_UnregisterClass(g_classID);
}

public Action CodD0_ClassChanged(int client, int classID) {
	if(g_classID != classID && g_hasClass[client]) {
		CodD0_SetClientRecoil(client, CodD0_SkillSlot_Class, 1.0);
		CodD0_SetClientChanceToThrowUp(client, CodD0_SkillSlot_Class, 0, 0.0, 0.0);
		CodD0_SetClientChanceToEnemySkin(client, CodD0_SkillSlot_Class, 0);
		g_hasClass[client] = false;
	}

	return Plugin_Continue;
}

public void CodD0_ClassChanged_Post(int client, int classID) {
	if(g_classID == classID) {
		CodD0_SetClientRecoil(client, CodD0_SkillSlot_Class, 0.0);
		CodD0_SetClientChanceToThrowUp(client, CodD0_SkillSlot_Class, 12, 300.0, 1.5625);
		CodD0_SetClientChanceToEnemySkin(client, CodD0_SkillSlot_Class, 1);
		g_hasClass[client] = true;
	}
}